services:
  backend:
    build:
      context: packages/backend
      dockerfile: Dockerfile
      # these args configure private env vars for the backend and public env vars for the frontend
      args:
        ADMIN_USER: ${ADMIN_USER}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
        DOMAIN_NAME: ${DOMAIN_NAME}

        CACHE_DOMAIN: ${CACHE_DOMAIN}
        MEDIA_DOMAIN: ${MEDIA_DOMAIN}

        SMTP_HOST: ${SMTP_HOST}
        SMTP_USER: ${SMTP_USER}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_PASSWORD: ${SMTP_PASSWORD}
        SMTP_FROM: ${SMTP_FROM}

        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DBNAME: ${POSTGRES_DBNAME}

        WEBPUSH_PRIVATE: ${WEBPUSH_PRIVATE}
        WEBPUSH_PUBLIC: ${WEBPUSH_PUBLIC}

        ENABLE_BSKY: ${ENABLE_BSKY}
        PDS_DOMAIN_NAME: ${PDS_DOMAIN_NAME}

        LOG_SQL_QUERIES: ${LOG_SQL_QUERIES:-}
        UPLOAD_LIMIT: ${UPLOAD_LIMIT:-}
        POSTS_PER_PAGE: ${POSTS_PER_PAGE:-}
        LOG_LEVEL: ${LOG_LEVEL:-}
        BLOCKLIST_URI: ${BLOCKLIST_URI:-}
        FRONTEND_PATH: ${FRONTEND_PATH:-}
        DISABLE_REQUIRE_SEND_EMAIL: ${DISABLE_REQUIRE_SEND_EMAIL:-}
        BLOCKED_IPS: ${BLOCKED_IPS:-}
        REVIEW_REGISTRATIONS: ${REVIEW_REGISTRATIONS:-}
        IGNORE_BLOCK_HOSTS: ${IGNORE_BLOCK_HOSTS:-}

        FRONTEND_LOGO: ${FRONTEND_LOGO:-}
        FRONTEND_API_URL: ${FRONTEND_API_URL:-}
        FRONTEND_MEDIA_URL: ${FRONTEND_MEDIA_URL:-}
        FRONTEND_CACHE_URL: ${FRONTEND_CACHE_URL:-}
        FRONTEND_SHORTEN_POSTS: ${FRONTEND_SHORTEN_POSTS:-}
        FRONTEND_DISABLE_PWA: ${FRONTEND_DISABLE_PWA:-}
        FRONTEND_MAINTENANCE: ${FRONTEND_MAINTENANCE:-}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./packages/backend/uploads:/wafrn/uploads
      - ./packages/backend/cache:/wafrn/cache
      - ./packages/frontend/src/index.html:/wafrn/packages/frontend/index.html

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        ADMIN_CONTACT_EMAIL: ${ADMIN_CONTACT_EMAIL}

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
    volumes:
      - dbpg:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always

  redis:
    image: redis:7.2.4
    restart: always

  caddy:
    build:
      context: packages/caddy
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        PDS_DOMAIN_NAME: ${PDS_DOMAIN_NAME}
        CACHE_DOMAIN: ${CACHE_DOMAIN}
        MEDIA_DOMAIN: ${MEDIA_DOMAIN}
        ACME_EMAIL: ${ACME_EMAIL}
    ports:
      - 80:80
      - 443:443
    volumes:
      - "caddy:/data"

  pds:
    image: ghcr.io/bluesky-social/pds:0.4
    environment:
      PDS_HOSTNAME: ${PDS_DOMAIN_NAME}
      PDS_JWT_SECRET: ${PDS_JWT_SECRET}
      PDS_ADMIN_PASSWORD: ${PDS_ADMIN_PASSWORD}
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ${PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX}
      PDS_DATA_DIRECTORY: /pds
      PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
      PDS_BLOB_UPLOAD_LIMIT: 52428800
      PDS_DID_PLC_URL: "https://plc.directory"
      PDS_BSKY_APP_VIEW_URL: "https://api.bsky.app"
      PDS_BSKY_APP_VIEW_DID: "did:web:api.bsky.app"
      PDS_REPORT_SERVICE_URL: "https://mod.bsky.app"
      PDS_REPORT_SERVICE_DID: "did:plc:ar7c4by46qjdydhdevvrndac"
      PDS_CRAWLERS: "https://bsky.network"
      LOG_ENABLED: true
    volumes:
      - pds:/pds

volumes:
  dbpg:
  caddy:
  pds:
